name: supaaaa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  date_field: ^6.0.3+1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LogoMedicall.png
    - assets/inventaris-icon.png
    - assets/jadwal-icon.png
    - assets/daftar-pasien-icon.png

